### ISSUE TITLE
Links to wrong beaconcha.in site for mainnet

### ISSUE THREAD

**Issue by Phistr90** [TurboLabIt/ethereum-autostaker#1]
Looking at the code it looks like it links to the wrong beaconcha.in site for mainnet mode.

https://github.com/TurboLabIt/ethereum-autostaker/blob/49eac62ba2ad4bfb59d0721952b163fb409dd422/ethereum-autostaker.sh#L295

**Comment by ZaneCEO** [comment]
Nice catch, thanks!
